name: Deploy Backend

on:
  push:
    branches:
      - main
      - backend-setup
    paths:
      - 'amplify/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli@latest
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          
      - name: Install Dependencies
        run: |
          cd amplify
          npm install
          
      - name: Deploy Backend
        run: |
          cd amplify
          npm run deploy
